version: "3.9"

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    env_file:
      - .env      # можно убрать на Railway, если используешь Variables
    restart: unless-stopped
